// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCMkRF6sv_ycxKJcK-sS3M7XsKR4y-CBQ',
    appId: '1:764206559936:android:4959b42bc74b1c9a477325',
    messagingSenderId: '764206559936',
    projectId: 'cruizr-778a0',
    storageBucket: 'cruizr-778a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wt878fkuF3lM5I5DJCn_nwIXNGkHEsk',
    appId: '1:764206559936:ios:339a55410b237daa477325',
    messagingSenderId: '764206559936',
    projectId: 'cruizr-778a0',
    storageBucket: 'cruizr-778a0.firebasestorage.app',
    iosClientId: '764206559936-nrsvt4ofv6t4v0e6ol30v1vjlha7v1r3.apps.googleusercontent.com',
    iosBundleId: 'com.cruizr.cruizr',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCngkv_WKGMb2rIrSxAQFSUzWVcsbazvc',
    appId: '1:764206559936:web:af95b5ba7f02a5a8477325',
    messagingSenderId: '764206559936',
    projectId: 'cruizr-778a0',
    authDomain: 'cruizr-778a0.firebaseapp.com',
    storageBucket: 'cruizr-778a0.firebasestorage.app',
    measurementId: 'G-R0NKE7KT1G',
  );

}